name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # master 브랜치에 push 될 때마다 실행됨

permissions:
  contents: write  # gh-pages 브랜치에 write 권한

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true  # themes/typo 를 위해 필요
          fetch-depth: 0    # 전체 git 기록을 가져옴 (submodule 동기화 위함)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Generate static site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.hisun.cloud
